### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by repollo** [ollama-interface/Ollama-Gui#1]
Missing to document that it needs `rustc` and `cargo` tools from the rust language.

Additionally would it be possible to add the generated .dmg and executables to the repo's release tab?

**Comment by TwanLuttik** [comment]
I have added rust to the requirements, and yes that would be useful to build executable for Macos and Linux

**Comment by repollo** [comment]
@TwanLuttik, given our discussion on automating the build and release process, I've outlined a potential approach using GitHub Actions:

1. **Setting Up GitHub Actions**:
   - We can create a `.github/workflows` directory in the repository.
   - Then, a new YAML file can be added inside this directory, say `build-and-deploy.yml`.

2. **Building the Project**:
   The workflow should define steps to:
   - Set up the environment (NodeJS, Rust, etc.).
   - Run the build commands.
   - Archive the generated binaries.

   ```yaml
   # Sample steps for building
   jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          pnpm i

      - name: Build for MacOS
        run: pnpm build:app:silicon
        # Repeat similar steps for other platforms

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-silicon
          path: src-tauri/target/release/bundle/dmg/*.dmg
   ```


3. **Releasing on GitHub**:
   After building, we can:
   - Create a new GitHub release.
   - Attach the generated binaries to the release.

   ```yaml
   # Sample steps for release
   jobs:
    release:
      needs: build
      runs-on: ubuntu-latest

      steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-silicon

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-silicon/*.dmg
          asset_name: Ollama-Gui-MacOS-Silicon.dmg
          asset_content_type: application/octet-stream
   ```

4. **Workflow Trigger**:
   Ideally, this workflow could be triggered on every push to the `main` branch or when a new tag is created:

   ```yaml
   on:
     push:
       branches:
         - main
     tags:
       - '*'
   ```

5. **Tokens & Secrets**:
   We'd need to ensure the `GITHUB_TOKEN` (provided by default) is available for the release steps.

6. **Testing**:
   Before finalizing, we should test the workflow multiple times to ensure its reliability.

7. **Additional Considerations**:
   - Parallel builds for different platforms might speed things up.
   - We can think about adding notifications to stay informed about any build or deployment issues.

This approach would automate our build and release process, ensuring that every new version automatically uploads the appropriate executables for each platform to the repo's release tab. What are your thoughts? I haven't tried on my system yet but it should work if setup correctly.
